# fly.toml app configuration file generated for todoplanner on 2025-06-12T00:38:49+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todoplanner'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
